float:
  euclidean:
  - base_args: ['@metric']
    constructor: MariaDBInnodb
    disabled: false
    docker_tag: ann-benchmarks-mariadb_innodb
    module: ann_benchmarks.algorithms.mariadb_innodb
    name: mariadb_innodb
    run_groups:
      innodb:
        arg_groups: [{M: [3, 4, 5, 6, 8, 16, 32, 48], engine: 'InnoDB'}]
        args: {}
        query_args: [[1, 5, 10, 20, 40, 60, 100]]
